vim.o.termguicolors = true
vim.o.ttyfast = true
vim.o.autochdir = true
vim.o.exrc = true
vim.o.secure = false
vim.o.number = true
vim.o.relativenumber = true
vim.o.cursorline = true
vim.o.expandtab = false
vim.o.tabstop = 2
vim.o.smarttab = true
vim.o.shiftwidth = 2
vim.o.softtabstop = 2
vim.o.autoindent = true
vim.o.list = true
vim.o.scrolloff = 4
vim.o.sidescrolloff = 5
vim.o.viewoptions = "cursor,folds,slash,unix"
vim.o.wrap = true
vim.o.textwidth = 0
vim.o.indentexpr = ""
vim.o.foldmethod = "indent"
-- vim.o.fillchars = [[eob: ,fold: ,foldopen:,foldsep: ,foldclose:]]
vim.o.foldcolumn = "1" -- '0' is not bad
vim.o.foldlevel = 99
vim.o.foldenable = true
vim.o.foldlevelstart = 99
vim.o.formatoptions = vim.o.formatoptions:gsub("tc", "")
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.showmode = false
vim.o.linebreak = true
vim.o.breakindent = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.shortmess = vim.o.shortmess .. "c"
vim.o.inccommand = "split"
-- vim.o.completeopt = "longest,noinsert,menuone,noselect,preview"
-- vim.o.completeopt = "menu,menuone,noinsert,noselect,preview"
vim.o.completeopt = "menu,menuone,noinsert"
-- vim.o.lazyredraw = true
vim.o.visualbell = true
vim.o.colorcolumn = "81"
vim.o.smoothscroll = true
vim.o.updatetime = 100
vim.o.virtualedit = "block"
-- vim.g.maplocalleader = "  "
vim.o.jumpoptions = "stack"
vim.o.mousemoveevent = true
vim.o.mouse = "a"
--- popupmenu settings
vim.o.pumblend = 12
vim.o.pumheight = 12
